### PR TITLE
Better loading constant file

### PR DESCRIPTION
**Pull request by ChiefChippy2**
- Resolved an issue where getPrices would indefinitely fail 
- Added retries to allow for multiple retries instead of failing immediately
- Better handling for concurrence (maybe)

### CODE REVIEW

**Review by DuckySoLucky — APPROVED** [review]
lgtm, didn't test

**Review by MattTheCuber — APPROVED** [review]
lgtm, didnt test. Although probably didn't need to push changes to `package-lock.json`

**Comment by HOursH** [comment]
I support this code merge request as I often crash my code due to timeout failing to get the latest price lol

**Comment by ChiefChippy2** [comment]
> I support this code merge request as I often crash my code due to timeout failing to get the latest price lol

you can probably install this branch instead of the current npm version lmao if it rly crashes often
or set cache time longer

**Comment by MattTheCuber** [comment]
@Altpapier

**Comment by DuckySoLucky** [comment]
@Altpapier

**Comment by HOursH** [comment]
@Altpapier

**Comment by MattTheCuber** [comment]
Lol

**Comment by DuckySoLucky** [comment]
average SkyCrypt PR review time

**Comment by MattTheCuber** [comment]
I am going to test this later. Also probably shouldn't push changes to `package-lock.json`

**Comment by ChiefChippy2** [comment]
> I am going to test this later. Also probably shouldn't push changes to `package-lock.json`

https://docs.npmjs.com/cli/v10/configuring-npm/package-lock-json#description
>>> This file is intended to be committed into source repositories, and serves various purposes:

Describe a single representation of a dependency tree such that teammates, deployments, and continuous integration are guaranteed to install exactly the same dependencies.

Provide a facility for users to "time-travel" to previous states of node_modules without having to commit the directory itself.

Facilitate greater visibility of tree changes through readable source control diffs.

Optimize the installation process by allowing npm to skip repeated metadata resolutions for previously-installed packages

**Comment by MattTheCuber** [comment]
🤷‍♂️ fine by me ig

**Comment by MattTheCuber** [comment]
Man I've been putting this off 😬

**Review by MattTheCuber — APPROVED** [review]
lgtm, I tested, @Altpapier

One comment, should you wait like 100-500 ms between retries in case its a network issue or nah?

**Comment by Kathund** [comment]
@MattTheCuber is this ever getting merged? any update on this? I might just end up making a hypixel-api-reborn fork with this patch so we can have this patched and have the latest prices.

**Comment by MattTheCuber** [comment]
*hopefully alt doesnt get upset 😬*

wont be a npm release for a month or so btw

**Pull request merged**
