### PR TITLE
Add Typescript types for TS users

### PR DESCRIPTION
**Pull request by Kathund**
Added Types for the TypeScript Users of the package. This will make it easier to work with and support more users who want to use this package.

### CODE REVIEW

**Review by MattTheCuber — APPROVED** [review]
I don't know typescript that well, but I don't see any issues XD

**Comment by DuckySoLucky** [comment]
Wouldn't JSDoc be better? also can you types for objects like enchantments and attributes too

For reference: https://github.com/Altpapier/SkyHelper-Networth/pull/18

**Comment by Kathund** [comment]
> I don't know typescript that well, but I don't see any issues XD

A Typescript types file is required when working with typescript. This is useful to have autocomplete/intellisense working and also have return types so the end user dosen't need to work out what the code is going to return and maybe build one for them self.

Example of the reason why a typescript type file is required with typescript

https://github.com/Altpapier/SkyHelper-Networth/assets/55346310/aa2e17a9-e5e8-4206-81bd-f1c97d343f90

> Wouldn't JSDoc be better?

We already have JSDoc comments in some files. These are good because it allows for autocomplete/intellisense in javascript code.

> also can you types for objects like enchantments and attributes too

Sure i guess. This was kinda rushed coz i wanted to work with the package and typescript

**Review by MattTheCuber — APPROVED** [review]
@Altpapier

**Pull request merged**
